#ifndef 21AKTIENKURSNEW_GLOBAL_H
#define 21AKTIENKURSNEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(21AKTIENKURSNEW_LIBRARY)
#  define 21AKTIENKURSNEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define 21AKTIENKURSNEWSHARED_EXPORT Q_DECL_IMPORT
#endif




#endif // 21AKTIENKURSNEW_GLOBAL_H
